status:
  {{- $progressStatus := "" }}
  {{- $availableStatus := "" }}
  {{- $message := "" }}
  state: 
  {{- range .Values.deployment.status.conditions }} 
    {{- if eq .type "Progressing" }}
      {{- $progressStatus = .status }}
    {{- end }}
    {{- if eq .type "Available" }}
      {{- $availableStatus = .status }}
      {{- $message = .message }}
    {{- end }}
  {{- end }}
  {{- if and ( eq $progressStatus "True" ) ( eq $availableStatus "True" ) }}
    {{- " succeeded" }}
  {{- else }}
    {{- if and ( eq $progressStatus "True" ) ( eq $availableStatus "False" ) }}
      {{- " in progress" }}
    {{- else }}
      {{- " failed" }}
    {{- end }}
  {{- end }}
  response: {{ $message | quote }}