{{ $name := "" }}
{{- with .instance.metadata.name }} {{ $name = . }} {{ end }}
{{- $state := "in_queue" }}
{{- with .instance.metadata.labels.state }} {{ $state = . }} {{ end }}
{{- $serviceId := "" }}
{{- $planId := "" }}
{{- $organizationGuid := "" }}
{{- $spaceGuid := "" }}
{{- $context := "{}" }}
{{- $params := "{}" }}
{{- with .instance.spec }}
  {{- $serviceId = .serviceId }}
  {{- $plan_id = .planId }}
  {{- $organization_guid = .organizationGuid }}
  {{- $space_guid = .spaceGuid }}
  {{- $context = (printf "%s" .context) }}
  {{- $params = (printf "%s" .parameters) }}
{{- end }}
apiVersion: deployment.servicefabrik.io/v1alpha1
kind: Director
metadata:
  labels:
    state: {{ $state }}
  name: {{ $name }}
spec:
  options: {{ (printf `"{ \"service_id\": \"%s\", \"plan_id\": \"postgres\", \"organization_guid\": \"%s\", \"space_guid\": \"%s\", \"context\": \"%s\", \"parameters\": \"%s\" }"` $serviceId $planId $organizationGuid $spaceGuid $context $params ) }}