apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: sfservicebindings.osb.servicefabrik.io
spec:
  group: osb.servicefabrik.io
  names:
    kind: SFServiceBinding
    plural: sfservicebindings
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            acceptsIncomplete:
              type: boolean
            appGuid:
              type: string
            bindResource:
              type: object
            context:
              type: object
            id:
              type: string
            instanceId:
              type: string
            parameters:
              type: object
            planId:
              type: string
            serviceId:
              type: string
          required:
          - instanceId
          - planId
          - serviceId
          type: object
        status:
          properties:
            error:
              type: string
            response:
              properties:
                secretRef:
                  type: string
              type: object
            state:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
