version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/broker/applications/admin"
    schedule:
      interval: "weekly"
      day: "monday"
    ignore:
      - dependency-name: bluebird
      - dependency-name: ajv
      - dependency-name: rxjs
      - dependency-name: pkgcloud
      - dependency-name: dockerode
      - dependency-name: kubernetes-client
      - dependency-name: agenda
  - package-ecosystem: "docker"
    directory: "/broker"
    schedule:
      interval: "weekly"
      day: "monday"
  - package-ecosystem: "docker"
    directory: "/interoperator"
    schedule:
      interval: "weekly"
      day: "monday"
   
