---
matrix:
  include:
    - language: go
      os:
        - linux
      go:
        - "1.11"
      git:
        depth: 3
      before_install:
        - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      install:
        - cd interoperator
        - dep ensure -v
        - cd ../webhooks
        - dep ensure -v
        - cd ..
      script:
        - pushd interoperator
        - ./scripts/install_test.sh
        - go test -v -coverpkg=./pkg/... -coverprofile=coverage.txt ./pkg/...
        - popd
        - pushd webhooks
        - go test -v -coverpkg=./pkg/webhooks/... -coverprofile=coverage.txt ./pkg/webhooks/manager/...
        - popd
        - cat interoperator/coverage.txt webhooks/coverage.txt > coverage.txt
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - language: go
      os:
        - linux
      go:
        - "1.11"
      git:
        depth: 3
      before_install:
        - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        - go get golang.org/x/lint/golint
      install:
        - cd interoperator
        - dep ensure -v
        - cd ../webhooks
        - dep ensure -v
        - cd ..
      script:
        - pushd interoperator
        - go fmt ./pkg/... ./cmd/...
        - go vet ./pkg/... ./cmd/...
        - golint ./pkg/... ./cmd/...
        - popd
        - pushd webhooks
        - go fmt ./pkg/webhooks/manager/... ./pkg/apis/...
        - go vet ./pkg/webhooks/manager/... ./pkg/apis/...
        - golint ./pkg/webhooks/manager/... ./pkg/apis/...
        - popd
    - language: node_js
      node_js:
        - "8.14"
      env:
        - SETTINGS_PATH="$(pwd)/broker/config/settings.yml"
      script:
        - "npm run -s test-coverall"
    - language: node_js
      node_js:
        - "8.14"
      env:
        - SETTINGS_PATH="$(pwd)/broker/config/settings.yml"
      script:
        - |
          IFS='' CHANGED_FILES=$(npm run -s jsformat -- | grep -v "unchanged")
          [[ -z $CHANGED_FILES ]] && NUM_CHANGED_FILES=0 || NUM_CHANGED_FILES=$(echo $CHANGED_FILES | wc -l)
          echo "Code formatting to be fixed in $NUM_CHANGED_FILES file(s)..."
          if [[ $NUM_CHANGED_FILES -gt 0 ]]; then
            echo "Listing modifications required.."
            git diff
            echo "FAILED: Run js-beautify(npm run jsformat)" && exit 1;
          else
            echo "No changes to the code formatting required.. "
          fi
        - "npm run -s jshint-ci"
        - "npm run -s jsdoc"
    - language: node_js
      node_js:
        - "8.14"
      before_install:
        - pip install --user truffleHog==2.0.89
        - |
          pushd /tmp
          git clone --depth 1 https://github.com/awslabs/git-secrets
          cd git-secrets
          sudo make install
          popd
      script:
        - |
          git secrets --install
          git secrets --register-aws --global
          git secrets --list
        - |
          git secrets --scan-history || exit 1
        - |
          echo "Full repo scan of truffleHog"
          # truffleHog only scans git endpoints which have a ref.
          # truffleHog check fails to detect changed because travis merge creates a detached HEAD
          # Creating a branch to fix this issue
          git checkout -b travis-merge
          INITIAL_COMMIT="a1206f7a64978e70441460f9f907c2904909a531"
          high_entropy=$(trufflehog --json --entropy true --max_depth 1 --regex "$TRAVIS_BUILD_DIR")
          echo "Truffle hog output : $high_entropy"
          if [[ "$high_entropy" != "" ]] ; then exit 1; fi
