---
language: node_js
node_js:
  - "6.9"
script:
  - |
     IFS='' CHANGED_FILES=$(npm run -s jsformat -- | grep -v "unchanged")
     [[ -z $CHANGED_FILES ]] && NUM_CHANGED_FILES=0 || NUM_CHANGED_FILES=$(echo $CHANGED_FILES | wc -l)
     echo "Code formatting to be fixed in $NUM_CHANGED_FILES file(s)..."
     if [[ $NUM_CHANGED_FILES -gt 0 ]]; then
       git diff
       echo "Listing modifications required.."
       echo "FAILED: Run js-beautify(npm run jsformat)" && exit 1;
     else
       echo "No changes to the code formatting required.. "
     fi
  - "npm run -s jshint-ci"
  - "npm run -s test-ci"
  - "npm run -s jsdoc"
