---
language: node_js
node_js:
  - "6.9"
before_install:
  - pip install --user truffleHog
  - |
    pushd /tmp
    git clone --depth 1 https://github.com/awslabs/git-secrets
    cd git-secrets
    sudo make install
    popd
env:
  - SETTINGS_PATH="$(pwd)/config/settings.yml"
script:
  - |
     git secrets --install
     git secrets --register-aws --global
     git secrets --list
     IFS='' CHANGED_FILES=$(npm run -s jsformat -- | grep -v "unchanged")
     [[ -z $CHANGED_FILES ]] && NUM_CHANGED_FILES=0 || NUM_CHANGED_FILES=$(echo $CHANGED_FILES | wc -l)
     echo "Code formatting to be fixed in $NUM_CHANGED_FILES file(s)..."
     if [[ $NUM_CHANGED_FILES -gt 0 ]]; then
       echo "Listing modifications required.."
       git diff
       echo "FAILED: Run js-beautify(npm run jsformat)" && exit 1;
     else
       echo "No changes to the code formatting required.. "
     fi
  - "npm run -s jshint-ci"
  - "npm run -s test-ci"
  - "npm run -s jsdoc"
  - |
     git secrets --scan-history || exit 1
  - |
     echo "Full repo scan of truffleHog"
     trufflehog --json --entropy true ./
     high_entropy=$(trufflehog --json --entropy true --regex ./)
     echo "Truffle hog output : $high_entropy"
     [[ -n "$high_entropy" ]] && exit 1
