{{ $stateString := "" }}
{{- if eq .Values.postgresql.status.phase "Failed" }}
  {{- $stateString = "failed" }}
{{- else }}
  {{- if eq .Values.postgresql.status.phase "Running"}}
    {{- $stateString = "succeeded" }}
  {{- else }}
    {{- $stateString = "in progress" }}
  {{- end }}
{{- end }}
status:
  state: {{ $stateString | quote }}  
  response: {{ .Values.postgresql.status.reason | quote }}
  lastOperation: {{ (printf "{ \"state\": \"%s\", \"description\": \"%s\" }" $stateString .Values.postgresql.status.reason) | quote }}