general:
    buildTool: docker
    productiveBranch: 'master'
    githubApiUrl: 'https://api.github.com'
    githubServerUrl: 'https://github.com'
    gitHttpsCredentialsId: GithubOsCredentialsId
    verbose: true
    
steps:
    kanikoExecute:
        dockerConfigJsonCredentialsId: DockerHubCredentialsId
        containerImage: docker.io/servicefabrikjenkins/service-fabrik-broker:kaniko
        dockerfilePath: 'broker/Dockerfile'
