apiVersion: osb.servicefabrik.io/v1alpha1
kind: SfPlan
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    serviceId: '24731fb8-7b84-4f57-914f-c3d55d793dd4'
  name: &name 'v1.0-xsmall'
spec:
  name: *name
  id: 'e86e2cf2-569a-11e7-a2e3-02a8da424bc3'
  description: 'Blueprint 1.0 service x-small (managed service in beta)'
  metadata:
    service-inventory-key: SERVICE-161
    costs:
    - amount:
        usd: 0.0
      unit: 'MONTHLY'
    bullets:
    - 'Dedicated Deployment'
    - '1 VM'
    - '1 vCPUs'
    - '1 GB Memory'
    - '1 GB Disk'
  free: false
  bindable: true
  planUpdatable: false
  templates:
  - action: properties
    type: helm
    url: "config/samples/templates/blueprintProperties"
  - action: provision
    type: helm
    url: "config/samples/templates/blueprint"
  - action: bind
    type: helm
    url: "config/samples/templates/blueprint"
  serviceId: '24731fb8-7b84-4f57-914f-c3d55d793dd4'
  manager:
    async: true
  context:
    operator:
      image: "servicefabrikjenkins/blueprint"
      tag: "latest"
      port: 8080
      memory: '1g'
      persistent_volumes:
      - name: 'data'
        path: '/data'
        size: '1g'
    serviceFabrik:
      backupEnabled: true
