apiVersion: osb.servicefabrik.io/v1alpha1
kind: SfPlan
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    serviceId: '24731fb8-7b84-5f57-914f-c3d55d793dd4'
  name: &name 'v9.4-dev'
spec:
  name: *name
  id: 'bba8beae-5699-12e7-b35c-02a8da424bc3'
  description: 'Postgresql service running inside a k8s container (for non-productive usage)'
  metadata:
    service-inventory-key: SERVICE-161
    costs:
    - amount:
        usd: 0.0
      unit: 'MONTHLY'
    bullets:
    - 'Container Deployment'
    - '128 MB Memory'
    - '100 MB Disk'
  free: true
  bindable: true
  planUpdatable: false
  templates:
  - action: sources
    type: helm
    url: "config/samples/templates/postgresqlProperties"
  - action: properties
    type: helm
    url: "config/samples/templates/postgresqlProperties"
  - action: provision
    type: helm
    url: "config/samples/templates/postgresql"
  - action: bind
    type: helm
    url: "config/samples/templates/postgresql"
  serviceId: '24731fb8-7b84-5f57-914f-c3d55d793dd4'
  manager:
    async: true
  context:
    operator:
      image: "servicefabrikjenkins/blueprint"
      tag: "latest"
      port: 8080
      memory: '128m'
      persistent_volumes:
      - name: 'data'
        path: '/data'
        size: '100m'
    serviceFabrik:
      backupEnabled: false
