apiVersion: osb.servicefabrik.io/v1alpha1
kind: SfPlan
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    serviceId: '24731fb8-7b84-4f57-914f-c3d55d793dd4'
  name: &name 'v1.0-dev-large'
spec:
  name: *name
  id: 'a66844e2-5699-11e7-93cc-02a8da424bc3'
  description: 'Blueprint 1.0 service running inside a large Docker container (for non-productive usage)'
  metadata:
    service-inventory-key: SERVICE-161
    costs:
    - amount:
        usd: 0.0
      unit: 'MONTHLY'
    bullets:
    - 'Container Deployment'
    - '256 MB Memory'
    - '200 MB Disk'
  free: true
  bindable: true
  planUpdatable: false
  templates:
  - action: properties
    type: helm
    url: "config/samples/templates/blueprintProperties"
  - action: provision
    type: helm
    url: "config/samples/templates/blueprint"
  - action: bind
    type: helm
    url: "config/samples/templates/blueprint"
  serviceId: '24731fb8-7b84-4f57-914f-c3d55d793dd4'
  manager:
    async: true
  context:
    operator:
      image: "servicefabrikjenkins/blueprint"
      tag: "latest"
      port: 8080
      memory: '256m'
      persistent_volumes:
      - name: 'data'
        path: '/data'
        size: '200m'
    serviceFabrik:
      backupEnabled: false
