apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: serviceinstances.interoperator.servicefabrik.io
spec:
  group: interoperator.servicefabrik.io
  names:
    kind: ServiceInstance
    plural: serviceinstances
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            options:
              type: string
          type: object
        status:
          properties:
            dashboardUrl:
              type: string
            error:
              format: byte
              type: string
            lastOperation:
              format: byte
              type: string
            response:
              format: byte
              type: string
            state:
              type: string
          required:
          - state
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []