http:
  error_threshold_percentage: 49
  service_timeout: 4000
  request_volume_threshold: 5
  sleep_window_in_ms : 30000
  statistical_window_length: 10000
  statistical_window_number_of_buckets: 10
  apis:
    "https://192.168.50.3:25555":
      name: "Boot Strap Bosh Director"
      error_threshold_percentage: 44
      service_timeout: 4000
      request_volume_threshold: 5
      sleep_window_in_ms : 30000
      statistical_window_length: 5000
      api_overrides:
        GET:
          error_threshold_percentage: 39
          service_timeout: 1000
          request_volume_threshold: 5
          method_overrides:
            "/info":
              error_threshold_percentage: 30
              service_timeout: 1000
              request_volume_threshold: 2
            "/deployments":
              error_threshold_percentage: 29
              service_timeout: 2000
              request_volume_threshold: 3  
        POST:
          error_threshold_percentage: 19
          service_timeout: 90000
          request_volume_threshold: 3
          method_overrides:
            "/deployments":
              error_threshold_percentage: 19
              service_timeout: 90000
              request_volume_threshold: 4
        PUT:
          error_threshold_percentage: 19
          service_timeout: 90000
          request_volume_threshold: 3
        DELETE:
          error_threshold_percentage: 19
          service_timeout: 90000
          request_volume_threshold: 3
    "https://192.168.50.4:25555":
      name: "Bosh Director"
      error_threshold_percentage: 44
      service_timeout: 4000
      request_volume_threshold: 5
      sleep_window_in_ms : 30000
      statistical_window_length: 5000
      api_overrides:
        GET:
          error_threshold_percentage: 39
          service_timeout: 1000
          request_volume_threshold: 5
          method_overrides:
            "/info":
              error_threshold_percentage: 30
              service_timeout: 1000
              request_volume_threshold: 2
            "/deployments":
              error_threshold_percentage: 29
              service_timeout: 2000
              request_volume_threshold: 3  
        POST:
          error_threshold_percentage: 19
          service_timeout: 90000
          request_volume_threshold: 3
          method_overrides:
            "/deployments":
              error_threshold_percentage: 19
              service_timeout: 90000
              request_volume_threshold: 4
        PUT:
          error_threshold_percentage: 19
          service_timeout: 90000
          request_volume_threshold: 3
        DELETE:
          error_threshold_percentage: 19
          service_timeout: 90000
          request_volume_threshold: 3
    "https://api.bosh-lite.com":
      name: "Cloud Controller"
      service_timeout: 5000
      request_volume_threshold: 5
      sleep_window_in_ms : 60000
    "https://uaa.bosh-lite.com":
      name: "CF UAA"
      service_timeout: 5000
      request_volume_threshold: 5
      sleep_window_in_ms : 60000