---
azs:
- name: z1
- name: z2
- name: z3

vm_types:
- name: default
- name: micro

disk_types:
- name: default
  disk_size: 1024
- name: hdd_1gb
  disk_size: 1024

networks:
- name: compilation
  type: dynamic
- name: default
  type: manual
  subnets:
  - dns: [8.8.8.8]
    range: 10.244.0.0/20
    gateway: 10.244.0.1
    static: [10.244.0.2 - 10.244.15.254]
    reserved: [10.244.0.1, 10.244.15.255]

compilation:
  workers: 5
  reuse_compilation_vms: true
  vm_type: default
  network: compilation