---
message_bus_servers:
- host: 10.244.0.6:4222
  user: nats
  password: nats
host: 10.0.2.2
routes:
- name: fabrik
  port: 9292
  uris:
  - service-fabrik-broker.bosh-lite.com
  registration_interval: 20s
