{{ $randomString := randAlphaNum 5 | quote -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Release.Name }}-broker
  name: {{ .Release.Name }}-broker-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.broker.service.type }}
  ports:
  - name: http
    port: 80
    targetPort: broker-internal
  - name: https
    port: 443
    targetPort: broker-internal
  selector:
    app: {{ .Release.Name }}-broker
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    service: {{ .Release.Name }}-broker
    {{- if .Values.cluster.ssl }}
    garden.sapcloud.io/purpose: managed-cert
    {{- end }}
  name: {{ .Release.Name }}-broker-service-ingress
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: {{ .Values.cluster.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-broker-service
          servicePort: 80
  {{- if .Values.cluster.ssl }} 
  tls:
  - hosts:
    - {{ .Values.cluster.host }}
    secretName: {{ .Values.cluster.sslsecret }}
  {{- end }} 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-broker
  labels:
    app: {{ .Release.Name }}-broker
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-broker
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-broker
        rollme: {{ $randomString }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: {{ .Release.Name }}-broker
            rollme: {{ $randomString }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.broker.image.repository }}:{{ .Values.broker.image.tag }}"
        imagePullPolicy: {{ .Values.broker.image.pullPolicy }}
        ports:
        - name: broker-internal
          containerPort: {{ .Values.broker.port }}
          protocol: TCP
        env:
        - name: NODE_ENV
          value: kubernetes
        - name: SETTINGS_PATH
          value: /opt/sf-config/settings.yml
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: BROKER_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-creds
              key: broker_username
        - name: BROKER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-creds
              key: broker_password
        - name: QUOTA_APP_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-creds
              key: quota_app_username
        - name: QUOTA_APP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-creds
              key: quota_app_password
        - name: QUOTA_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-creds
              key: quota_username
        - name: QUOTA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-creds
              key: quota_password
        volumeMounts:
        - name: settings
          mountPath: /opt/sf-config
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9293
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9293
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        args:
        - applications/osb-broker/src/server.js
        command:
        - node 
      volumes:
        - name: settings
          configMap:
            name: sf-settings-config
      restartPolicy: Always
