apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Release.Name }}-quota
  name: {{ .Release.Name }}-quota-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.quota_app.service.type }}
  ports:
  - name: http
    port: 80
    targetPort: quota-app-port
  selector:
    app: {{ .Release.Name }}-quota-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-quota-app
  labels:
    app: {{ .Release.Name }}-quota-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-quota-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-quota-app
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.quota_app.image.repository }}:{{ .Values.quota_app.image.tag }}"
        imagePullPolicy: {{ .Values.quota_app.image.pullPolicy }}
        ports:
        - name: quota-app-port
          containerPort: {{ .Values.quota_app.port }}
          protocol: TCP
        env:
        - name: NODE_ENV
          value: kubernetes
        - name: SETTINGS_PATH
          value: /opt/sf-config/settings.yml
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: settings
          mountPath: /opt/sf-config
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9296
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9296
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        args:
        - applications/quota-app/src/index.js
        command:
        - node 
      volumes:
        - name: settings
          configMap:
            name: sf-settings-config
      restartPolicy: Always
